# Generated by Django 5.2.7 on 2025-10-27 10:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.JSONField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorLanguage', to='api.doctorname')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctors/')),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorDetail', to='api.doctorname')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorExperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experties', models.JSONField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorExperties', to='api.doctorname')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromyear', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('toyear', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('position', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorExperience', to='api.doctorname')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromyear', models.PositiveIntegerField()),
                ('toyear', models.PositiveIntegerField()),
                ('course', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('Discription', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorEducation', to='api.doctorname')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorContact', to='api.doctorname')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.JSONField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorCertificate', to='api.doctorname')),
            ],
        ),
        migrations.CreateModel(
            name='TreatOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('items', models.JSONField()),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.treatment')),
            ],
        ),
    ]
